local handler = require("event_handler")
handler.add_lib(require("__factorio-scv-control__/scenarios/scv-control-test/test-lab"))
handler.add_lib(require("pathfinding.runtime"))
handler.add_lib(require("interchange.runtime"))
handler.add_lib(require("interchange.live"))
handler.add_lib(require("savebench.runtime"))
handler.add_lib(require("comparison.runtime"))
handler.add_lib(require("unified.runtime"))
